Make nova-c-c the coordinator of SSH authentication among compute nodes.

diff --git a/hooks/nova-cloud-controller-common b/hooks/nova-cloud-controller-common
--- a/hooks/nova-cloud-controller-common
+++ b/hooks/nova-cloud-controller-common
@@ -13,7 +13,7 @@ if [[ -n "$n_vol" ]] ; then
   dpkg -l | grep -q nova-api-os-volume || apt-get -y install nova-api-os-volume
 fi
 
-PACKAGES="$SERVICES python-mysqldb python-keystone uuid"
+PACKAGES="$SERVICES python-mysqldb python-keystone apache2 uuid"
 
 NET_MANAGER=$(config-get network-manager)
 if [ "$NET_MANAGER" == "Quantum" ]; then
@@ -62,4 +62,121 @@ function configure_quantum_networking {
                     -f $(config-get pool-floating-start):$(config-get pool-floating-end) \
                     $(config-get ext-net-name)
   fi
+}
+
+function ssh_authorized_keys {
+  local key="$1"
+  local action="$2"
+  local exists=""
+
+  local sunit=$(echo $JUJU_REMOTE_UNIT | cut -d/ -f1)
+  mkdir -p /etc/nova/compute_ssh/$sunit
+  local authorized_keys="/etc/nova/compute_ssh/$sunit/authorized_keys"
+
+  [[ -e "$authorized_keys" ]] &&
+    grep -q "^$key" $authorized_keys && exists="true"
+
+  if [[ "$action" == "add" ]] ; then
+    [[ -n "$exists" ]] &&
+      juju-log "$CHARM: SSH key already authorized for $JUJU_REMOTE_UNIT." &&
+        return 0
+
+    echo "$key" >>$authorized_keys
+    juju-log "$CHARM: Authorized new SSH key for $JUJU_REMOTE_UNIT."
+    return 0
+  elif [[ "$action" == "remove" ]] ; then
+    # we have no way of getting to the relation state during a departed hook.
+    # we only have the peer's unit name, so remove an authorized key based on
+    # its comment, which should can be derived from the remote unit name and
+    # gets passed in here from caller as key/$1
+    local key_ln=$(sed -n "\, ${key}$,=" $authorized_keys)
+    [[ -z "$key_ln" ]] &&
+      juju-log "$CHARM: Cannot remove SSH key for $key, not authorized?" &&
+        return 0
+
+    for ln in $key_ln ; do
+      sed -i "${ln}d" $authorized_keys
+      juju-log "$CHARM: Removed existing SSH key ($key) from authorized_keys."
+    done
+    return 0
+  else
+    error_out "$CHARM: ssh_authorize_keys() invalid action specified: $action."
+  fi
+}
+
+function ssh_known_hosts {
+  # Keeps the system-wide SSH known hosts file up to date with compute
+  # nodes host keys.
+  local host="$1"
+  local sunit=$(echo $JUJU_REMOTE_UNIT | cut -d/ -f1)
+  mkdir -p /etc/nova/compute_ssh/$sunit
+  local known_hosts="/etc/nova/compute_ssh/$sunit/known_hosts"
+  juju-log "$CHARM: Ensuring host is included and up to date in $known_hosts."
+
+  [[ ! -e $known_hosts ]] && touch $known_hosts
+
+  local remote_key=""
+  remote_key=$(ssh-keyscan -H -t rsa $host) ||
+    error_out "$CHARM: Couldn't obtain SSH host key from $host."
+  local existing=$(ssh-keygen -f $known_hosts -H -F $host | tail -n1)
+  if [[ -n "$existing" ]] ; then
+    juju-log "$CHARM: Found existing SSH known host key for $host."
+    [[ "$existing" == "$remote_key" ]] && echo "HI"
+    remote=$(echo $remote_key | awk '{ print $2" "$3 }')
+    existing=$(echo $existing | awk '{ print $2" "$3 }')
+    if [[ "$remote" == "$existing" ]] ; then
+      juju-log "$CHARM: SSH known host key for $host is up to date."
+      return 0
+    fi
+    juju-log "$CHARM: Removing outdated SSH host key for $host."
+    ssh-keygen -f $known_hosts -R $host
+  else
+    juju-log "$CHARM: No known hosts entry for $host."
+  fi
+  juju-log "$CHARM: Adding new SSH known hosts entry for $host."
+  echo $remote_key >>$known_hosts
+
+}
+
+function ssh_compute {
+  if [[ "$1" == "add" ]] ; then
+    local ssh_key=$(relation-get ssh_public_key)
+    [[ -z "$ssh_key" ]] &&
+      juju-log "$CHARM: ssh_compute peer not ready." && exit 0
+
+    ssh_authorized_keys "$ssh_key" "add"
+
+    # need to ensure known hosts entries for all possible addresses
+    . /usr/share/charm-helper/sh/net.sh
+    local known_hosts=""
+    local private_address=$(relation-get private-address)
+    known_hosts="$private_address"
+    if ! ch_is_ip "$private_address" ; then
+      known_hosts="$known_hosts $(get_ip $private_address)"
+      known_hosts="$known_hosts $(echo $private_address | cut -d. -f1)"
+    fi
+    for host in $known_hosts ; do
+      ssh_known_hosts "$host"
+    done
+  elif [[ "$1" == "remove" ]] ; then
+    # remove key by referencing remote unit, not entire key.
+    local remote_unit=$(echo $JUJU_REMOTE_UNIT | sed -e 's,/,-,g')
+    ssh_authorized_keys "$remote_unit" remove
+  else
+    error_out "ssh_compute: Invalid parameter: $1."
+  fi
+
+  local sunit=$(echo $JUJU_REMOTE_UNIT | cut -d/ -f1)
+  mkdir -p /var/www/compute_ssh/$sunit
+  cp /etc/nova/compute_ssh/$sunit/known_hosts \
+    /var/www/compute_ssh/$sunit/known_hosts
+  cp /etc/nova/compute_ssh/$sunit/authorized_keys \
+    /var/www/compute_ssh/$sunit/authorized_keys
+
+  # MD5 sums should trigger new relation changes only when necessary
+  relation-set \
+    known_hosts_url="http://$(unit-get private-address)/compute_ssh/$sunit/known_hosts" \
+    known_hosts_md5="$(md5sum /var/www/compute_ssh/$sunit/known_hosts | awk '{ print $1 }')" \
+    authorized_keys_url="http://$(unit-get private-address)/compute_ssh/$sunit/authorized_keys" \
+    authorized_keys_md5="$(md5sum /var/www/compute_ssh/$sunit/authorized_keys | awk '{ print $1 }')"
 }
